feat: display notification if npm install is required
aditosoftware/adito-nb-nodejs pull request #4
Opened 2022-09-16 06:08 UTC by pas-n

2022-09-16 08:52 UTC, wglanzer requested changes

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +  public void fileDataCreated(FileEvent fe)
Readability: There is a class called "FileChangeAdapter", that implements all methods from the FileChangeListener-Interface so that you have do not have to implement ALL of them

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +public final class NpmInstallRequired implements FileChangeListener
Readability: Every public method should/must have a comment, describing what the method is expected to do

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +    packageJsonFo = project.getProjectDirectory().getFileObject("package.json");
What happens if the package.json was created while the project was opened? The listener never gets added?

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +  public void notifyIfRequired()
why is this method public? you do not use this outside of this class?

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +  public boolean isRequired()
why is this method public? you do not use this outside of this class?

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +  public void showNotification()
why is this method public? you do not use this outside of this class?

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +        e -> {
Readability: I think this code block should be a method with a describing comment.. This method itself looks a bit heavy..
Maybe you should extract it as a new utility-method, so that the code block can be reused in the install action?

2022-09-16 08:52 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +  public static NpmInstallRequired forProject(@NotNull Project pProject)
Add missing NotNull/Nullable annotations for return values

2022-09-16 09:25 UTC, pas-n commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/NpmInstallRequired.java
> +  public void notifyIfRequired()
it is used in the projecthook

2022-09-16 13:20 UTC, wglanzer requested changes

2022-09-16 13:20 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/actions/AbstractProjectAction.java
> +  private Project _findProject(Node[] pNodes)
Comment and Annotations missing

2022-09-16 13:20 UTC, wglanzer commented on src/main/java/de/adito/aditoweb/nbm/nodejs/impl/actions/AbstractProjectAction.java
> +    return _findProject(pNodes) != null;
Before your changes this enable()-Method checked, if there was a valid environment and executor. Is this behavior change expected?

2022-09-26 06:41 UTC, wglanzer approved these changes

2022-09-26 07:11 UTC, merged